blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ & í† ë¡ 
    url: https://github.com/Prometheus-P/ondacorea/discussions
    about: ê¸°ëŠ¥ ìš”ì²­ì´ë‚˜ ë²„ê·¸ê°€ ì•„ë‹Œ ì¼ë°˜ì ì¸ ì§ˆë¬¸ì€ Discussionsë¥¼ ì´ìš©í•´ ì£¼ì„¸ìš”.
  - name: ğŸ“š ë¬¸ì„œ
    url: https://github.com/Prometheus-P/ondacorea/wiki
    about: í”„ë¡œì íŠ¸ ë¬¸ì„œë¥¼ í™•ì¸í•´ ë³´ì„¸ìš”.
